import json
import logging
import os
from datetime import datetime
from typing import List, Optional

from models.task import Task

logger = logging.getLogger(__name__)

_ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(_ROOT_DIR, "data")
TASKS_FILE = os.path.join(DATA_DIR, "tasks.json")

# Slot for a warning message to surface in the UI after a load.
_load_warning: Optional[str] = None


class PersistenceError(Exception):
    """Raised when tasks cannot be written to disk."""


def pop_load_warning() -> Optional[str]:
    """Return and clear any warning generated by the most recent load_tasks() call."""
    global _load_warning
    msg, _load_warning = _load_warning, None
    return msg


def _ensure_data_dir() -> None:
    os.makedirs(DATA_DIR, exist_ok=True)


def _backup_corrupt_file() -> str:
    """Rename tasks.json to a timestamped backup and return the backup path."""
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    backup = TASKS_FILE.replace(".json", f".corrupt-{ts}.json")
    os.replace(TASKS_FILE, backup)
    return backup


def load_tasks() -> List[Task]:
    global _load_warning
    _ensure_data_dir()

    if not os.path.exists(TASKS_FILE):
        return []

    with open(TASKS_FILE, "r", encoding="utf-8") as f:
        try:
            raw_list = json.load(f)
        except json.JSONDecodeError:
            backup = _backup_corrupt_file()
            _load_warning = (
                f"tasks.json was unreadable and has been backed up as "
                f"'{os.path.basename(backup)}'. Starting with an empty task list."
            )
            logger.warning("Corrupt tasks.json backed up to %s", backup)
            return []

    # Per-record tolerance: skip records missing required fields
    tasks: List[Task] = []
    skipped = 0
    for item in raw_list:
        try:
            tasks.append(Task.from_dict(item))
        except (KeyError, TypeError) as exc:
            skipped += 1
            logger.warning("Skipping malformed task record (%s): %s", exc, item)

    # De-duplicate by id, keeping first occurrence
    seen: set = set()
    unique: List[Task] = []
    for task in tasks:
        if task.id not in seen:
            seen.add(task.id)
            unique.append(task)
        else:
            skipped += 1
            logger.warning("Dropping duplicate task id: %s", task.id)

    if skipped and not _load_warning:
        _load_warning = (
            f"{skipped} task record(s) were skipped due to missing fields or "
            "duplicate IDs. Check application logs for details."
        )

    return unique


def save_tasks(tasks: List[Task]) -> None:
    """Atomically write tasks to disk via a temp file + os.replace()."""
    _ensure_data_dir()
    tmp_path = TASKS_FILE + ".tmp"
    try:
        with open(tmp_path, "w", encoding="utf-8") as f:
            json.dump([task.to_dict() for task in tasks], f, indent=2)
        os.replace(tmp_path, TASKS_FILE)
    except OSError as exc:
        raise PersistenceError(f"Could not save tasks to disk: {exc}") from exc
